name: Build Rust Implementation

on:
  push:
    branches:
      - canary
      - stable
    paths:
      - "packages/rust/**"
      - ".github/workflows/build-rust.yml"

jobs:
  build-rust:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Tests
        working-directory: packages/rust
        run: cargo test

      - name: Check
        working-directory: packages/rust
        run: cargo check
